baseURL = 'https://marco.longhin.org/'
languageCode = 'en-us'
title = 'marcobrb'
theme = 'xmin'

[[menu.main]]
name = "About Me"
url = ""
weight = 1

# [[menu.main]]
# name = "Manifest"
# url = "manifest"
# weight = 2

[[menu.main]]
name = "Blogs"
url = "blogs"
weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true